// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksxqdqycevtbmwetjtwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzeHFkcXljZXZ0Ym13ZXRqdHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Njk5MDAsImV4cCI6MjA3MjM0NTkwMH0.rgnVuYfcJ_9JQWf1Y8_QN8OTqpCxgCLVD9nUeEeW6Qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});